version: '3.8'
services:
  e2e_postgres:
    image: postgres:latest
    container_name: e2e_postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e2e_test_db
    volumes:
      - e2e_postgres_data:/var/lib/postgresql/data
  e2e_websockify:
    image: kamehb/websockify
    restart: unless-stopped
    command: "0.0.0.0:6433 e2e_postgres:5433"
    ports:
      - "6433:6432"
    depends_on:
      - e2e_postgres
    volumes:
      - e2e-websockify-data:/opt/websockify/data
      - e2e-websockify-config:/opt/websockify/config

volumes:
  e2e_postgres_data:
    driver: local
  e2e-websockify-data:
    driver: local
  e2e-websockify-config:
    driver: local
