export const metadata = {
<<<<<<< HEAD
  title: 'Next.js',
=======
  title: 'WCOA Volunteer Landing Page',
>>>>>>> origin/main
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
